/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#2a2a2a",
        "surface-container": "#1f1f1f",
        "inverse-on-surface": "#303030",
        "card-gradient-start": "#2A2A2E",
        "surface": "#131313",
        "card-gradient-end": "#101012",
        "secondary": "#c8c6c8",
        "on-tertiary-fixed-variant": "#454747",
        "on-primary": "#2f3131",
        "on-error": "#690005",
        "surface-container-lowest": "#0e0e0e",
        "on-background": "#e2e2e2",
        "surface-tint": "#c6c6c7",
        "surface-bright": "#393939",
        "tertiary-container": "#e2e2e2",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "secondary-container": "#474649",
        "on-secondary": "#303032",
        "inverse-primary": "#5d5f5f",
        "on-tertiary-fixed": "#1a1c1c",
        "primary-container": "#e2e2e2",
        "on-secondary-fixed-variant": "#474649",
        "on-secondary-fixed": "#1b1b1d",
        "on-surface": "#e2e2e2",
        "on-primary-container": "#636565",
        "tertiary-fixed-dim": "#c6c6c7",
        "primary-fixed-dim": "#c6c6c7",
        "background": "#131313",
        "surface-dim": "#131313",
        "text-muted": "#8E8E93",
        "inverse-surface": "#e2e2e2",
        "tertiary": "#ffffff",
        "surface-container-low": "#1b1b1b",
        "on-tertiary-container": "#636565",
        "surface-variant": "#353535",
        "on-primary-fixed-variant": "#454747",
        "secondary-fixed-dim": "#c8c6c8",
        "on-secondary-container": "#b7b4b7",
        "surface-container-highest": "#353535",
        "on-surface-variant": "#c4c7c8",
        "primary": "#ffffff",
        "secondary-fixed": "#e4e2e4",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary": "#2f3131",
        "primary-fixed": "#e2e2e2",
        "outline": "#8e9192",
        "on-error-container": "#ffdad6",
        "surface-secondary": "#141414",
        "outline-variant": "#444748",
        "on-primary-fixed": "#1a1c1c"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "container-margin": "24px",
        "gutter": "16px",
        "stack-overlap": "12px",
        "section-gap": "40px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
